name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=maranavard_SISTEMA-COMPUTACIONAL-PARA-LA-GESTION-Y-CONTROL-DE-ACCESO-DE-AUTOMOVILES-M-DULO-WEB
            -Dsonar.organization=maranavard
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          