sonar.projectKey=maranavard_SISTEMA-COMPUTACIONAL-PARA-LA-GESTION-Y-CONTROL-DE-ACCESO-DE-AUTOMOVILES-M-DULO-WEB
sonar.organization=maranavard

sonar.sources=python
sonar.tests=tests

sonar.python.version=3.12
