@startuml CU09_gestionar_espacios
actor "Administrador o Vigilante" as Actor
participant "UI Web" as UI
participant "EspaciosRoutes" as E
participant "EspacioModel" as M
database "PostgreSQL" as DB

Actor -> UI : Gestionar disponibilidad de cupos
UI -> E : GET /espacios
E -> M : list_items()
M -> DB : SELECT espacios
DB --> M : lista actual
M --> E : estado actual
E --> UI : panel espacios

UI -> E : POST /espacios/registrar
E -> M : upsert_by_numero()
M -> DB : INSERT/UPDATE espacio
DB --> M : ok/error
M --> E : resultado
E --> UI : confirmacion o error
@enduml
