@startuml CU02_actividad_consultar_reportes
title CU02 Consultar reportes
start
:Ingresar a Reportes;
:Elegir tipo de reporte;
if (Rol Vigilante/Seguridad) then (Si)
  :Forzar modulo Accesos/Salidas del dia;
endif
if (Hay datos) then (Si)
  :Visualizar resultados;
else (No)
  :Mostrar mensaje sin datos;
endif
stop
@enduml

