@startuml CU15_actividad_gestionar_vehiculo
title CU15 Gestionar vehiculo propio
start
:Abrir modulo Vehiculos;
:Consultar informacion del vehiculo;
if (Rol Administrador) then (Si)
  :Crear/editar registro;
  if (Placa disponible) then (Si)
    :Guardar vehiculo;
  else (No)
    :Mostrar placa duplicada;
  endif
else (No)
  :Mantener modo solo consulta;
endif
stop
@enduml

