@startuml CU19_actividad_consultar_estado_solicitud
title CU19 Consultar estado de solicitud
start
:Ingresar documento/datos;
:Intentar consultar estado;
:Mostrar funcionalidad pendiente;
stop
@enduml

