name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=maranavard_SISTEMA-COMPUTACIONAL-PARA-LA-GESTION-Y-CONTROL-DE-ACCESO-DE-AUTOMOVILES-M-DULO-WEB
            -Dsonar.organization=maranavard
            -Dsonar.python.version=3.12
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=python
            -Dsonar.tests=tests
            -Dsonar.exclusions=sql/sistema_control_backup.sql,**/sistema_control_backup.sql
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          